"""
Admin — Mock Tests (AI-generated exam-style assessments).

A mock test is a Quiz with quiz_type='mock' spanning selected chapters, a whole
subject, or a term (quarterly/half-yearly/annual). Generated by AI only.

POST   /api/admin/mock-tests/ai-generate   Generate a mock test (draft)
GET    /api/admin/mock-tests                List mock tests
Reuse for detail/publish/delete:
  GET    /api/admin/quiz/{id}
  PATCH  /api/admin/quiz/{id}/publish
  DELETE /api/admin/quiz/{id}
"""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List, Optional

from app.database import get_db
from app.dependencies import require_admin
from app.models.user import User
from app.models.quiz import Quiz, QuizQuestion, QuizStatus, MockTestChapter
from app.models.syllabus import Syllabus, Chapter
from app.models.category import Category
from app.schemas.quiz import MockTestGenerate, QuizResponse
from app.services.ai_quiz_service import generate_mock_test, AIQuizError

router = APIRouter()

_CONTENT_CHARS_PER_CHAPTER = 1800  # trim each chapter's content for the prompt


@router.get("", response_model=List[QuizResponse])
def list_mock_tests(
    category_id: Optional[int] = None,
    syllabus_id: Optional[int] = None,
    admin: User = Depends(require_admin),
    db: Session = Depends(get_db),
):
    q = db.query(Quiz).filter(Quiz.quiz_type == "mock")
    if category_id:
        q = q.filter(Quiz.category_id == category_id)
    if syllabus_id:
        q = q.filter(Quiz.syllabus_id == syllabus_id)
    quizzes = q.order_by(Quiz.created_at.desc()).all()
    out = []
    for quiz in quizzes:
        r = QuizResponse.from_orm(quiz)
        r.question_count = len(quiz.questions)
        out.append(r)
    return out


@router.post("/ai-generate", response_model=QuizResponse)
def ai_generate_mock_test(
    payload: MockTestGenerate,
    admin: User = Depends(require_admin),
    db: Session = Depends(get_db),
):
    cat = db.query(Category).filter(Category.id == payload.category_id).first()
    if not cat:
        raise HTTPException(status_code=404, detail="Category not found")

    if not payload.syllabus_ids:
        raise HTTPException(status_code=422, detail="Select at least one subject")
    subjects = (
        db.query(Syllabus)
        .filter(
            Syllabus.id.in_(payload.syllabus_ids),
            Syllabus.category_id == payload.category_id,
        )
        .all()
    )
    if not subjects:
        raise HTTPException(status_code=404, detail="Subjects not found in this category")
    subject_ids = [s.id for s in subjects]

    all_chapters = (
        db.query(Chapter)
        .filter(Chapter.syllabus_id.in_(subject_ids))
        .order_by(Chapter.syllabus_id, Chapter.order_index, Chapter.id)
        .all()
    )
    if payload.chapter_ids:
        wanted = set(payload.chapter_ids)
        chapters = [ch for ch in all_chapters if ch.id in wanted]
    else:
        chapters = all_chapters
    if not chapters:
        raise HTTPException(status_code=422, detail="No chapters found for the selected subjects")

    outlines = [
        {"title": ch.title, "content": (ch.description or "")[:_CONTENT_CHARS_PER_CHAPTER]}
        for ch in chapters
    ]

    subject_titles = [s.title for s in subjects]
    subject_label = (
        ", ".join(subject_titles)
        if len(subject_titles) <= 2
        else f"{len(subject_titles)} Subjects"
    )

    term = (payload.term or "").strip() or None
    if term:
        mock_scope = "term"
        scope_label = term.replace("_", " ").title()
    elif len(chapters) < len(all_chapters):
        mock_scope = "chapters"
        scope_label = f"{len(chapters)} Chapters"
    elif len(subjects) > 1:
        mock_scope = "subject"
        scope_label = "Multiple Subjects"
    else:
        mock_scope = "subject"
        scope_label = "Full Subject"

    try:
        result = generate_mock_test(
            scope_label=scope_label,
            chapter_outlines=outlines,
            num_questions=payload.num_questions,
            difficulty=payload.difficulty,
            marks_per_question=1,
            subject=subject_label,
        )
    except AIQuizError as e:
        raise HTTPException(status_code=502, detail=str(e))

    questions_data = result["questions"]
    if not questions_data:
        raise HTTPException(status_code=502, detail="AI returned no questions. Try again.")
    total = sum(q["marks"] for q in questions_data)
    pass_marks = (
        payload.pass_marks
        if payload.pass_marks and payload.pass_marks > 0
        else max(1, round(total * 0.33))  # exam-style pass ~33%
    )
    title = (payload.title or result["title"] or f"{subject_label} — {scope_label}").strip()

    quiz = Quiz(
        category_id=payload.category_id,
        syllabus_id=subjects[0].id,   # primary subject (for student grouping)
        quiz_type="mock",
        mock_scope=mock_scope,
        term=term,
        title=title[:200],
        description=f"Mock test — {subject_label} · {scope_label}",
        duration_mins=payload.duration_mins,
        total_marks=total,
        pass_marks=pass_marks,
        negative_marking=payload.negative_marking,
        status=QuizStatus.DRAFT,
        created_by=admin.id,
    )
    db.add(quiz)
    db.commit()
    db.refresh(quiz)

    db.add_all([QuizQuestion(quiz_id=quiz.id, **q) for q in questions_data])
    db.add_all([MockTestChapter(quiz_id=quiz.id, chapter_id=ch.id) for ch in chapters])
    db.commit()

    r = QuizResponse.from_orm(quiz)
    r.question_count = len(questions_data)
    return r
