"""add_subscription_payment_tables

Revision ID: f989131358a9
Revises: fix_userrole_enum_lc
Create Date: 2026-03-22 22:02:26.868268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f989131358a9'
down_revision: Union[str, Sequence[str], None] = 'fix_userrole_enum_lc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
