"""
AI Study Planner models.

Stores student AI preferences, chat messages, and daily study plans.
"""
import enum
from datetime import datetime, timezone, time as dt_time

from sqlalchemy import (
    Column, Integer, String, Text, Float, Boolean, Date,
    DateTime, Time, ForeignKey, JSON,
)
from sqlalchemy.orm import relationship

from app.database import Base


class AiStudentPreference(Base):
    """Student's AI study planner preferences (reminder time, study hours, etc.)"""
    __tablename__ = "ai_student_preferences"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False)
    daily_study_hours = Column(Float, default=2.0)
    reminder_time = Column(Time, default=dt_time(8, 0))  # Default 8:00 AM
    evening_reminder = Column(Boolean, default=False)
    is_enabled = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc),
                        onupdate=lambda: datetime.now(timezone.utc))

    # Relationships
    student = relationship("User", foreign_keys=[student_id])


class ChatRole(str, enum.Enum):
    USER = "user"
    ASSISTANT = "assistant"


class AiChatConversation(Base):
    """A conversation (session) grouping AI chat messages."""
    __tablename__ = "ai_chat_conversations"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    title = Column(String(100), default="New Chat")
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc),
                        onupdate=lambda: datetime.now(timezone.utc))

    student = relationship("User", foreign_keys=[student_id])
    messages = relationship("AiChatMessage", back_populates="conversation", cascade="all, delete-orphan")


class AiChatMessage(Base):
    """Individual chat messages between student and AI planner."""
    __tablename__ = "ai_chat_messages"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    conversation_id = Column(Integer, ForeignKey("ai_chat_conversations.id", ondelete="CASCADE"), nullable=True)
    role = Column(String(20), nullable=False)  # "user" or "assistant"
    content = Column(Text, nullable=False)
    metadata_json = Column(JSON, default=dict)  # deep links, plan refs, etc.
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    # Relationships
    student = relationship("User", foreign_keys=[student_id])
    conversation = relationship("AiChatConversation", back_populates="messages")


class AiStudyPlan(Base):
    """Daily study plan generated by AI for a student."""
    __tablename__ = "ai_study_plans"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    plan_date = Column(Date, nullable=False)
    tasks = Column(JSON, default=list)  # [{type, id, title, completed, ...}]
    summary = Column(Text)  # Human-readable summary for push notification
    generated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    completion_pct = Column(Float, default=0.0)

    # Relationships
    student = relationship("User", foreign_keys=[student_id])
